version: '2.4'

services:

  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:v2.3
    container_name: traefik
    network_mode: host
    ports:
      # The HTTP port
      - "80:80"
      # Docker sends requests on port 443 to Traefik on port 443
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8060:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ops/docker-compose/traefik/dynamic_conf.toml:/conf/dynamic_conf.toml
      - ./ops/docker-compose/traefik/traefik.toml:/traefik.toml

